sandbox:
  outputs:
    dev:
      dataset: sandboxa
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: udemy-sql-381210
      threads: 1
      type: bigquery
  target: dev
