name: deploy dbt

on:
  push:
    branches:
      - main

jobs:
  deploy-dbt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sandbox
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Authenticate with Google Cloud
        run: gcloud -v

      - name: Set project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: build Docker image to GAR
        run: docker build -t ${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dbt/dbt-image:latest .

      - name: push Docker image
        run: docker push ${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dbt/dbt-image:latest

      - name: deploy Cloud Run Jobs
        run: gcloud run jobs deploy dbt --image ${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dbt/dbt-image --region=${REGION} --tasks=1 --cpu=1 --max-retries=0 --memory=512Mi --parallelism=1 --task-timeout=600 --region ${REGION}

      - name: execute Cloud Run Jobs
        run: gcloud run jobs execute dbt --region=${REGION}
