name: deploy dbt

# on:
#   pull_request:
#     branches:
#       - main
on:
  push:
    branches:
      - main

jobs:
  deploy-dbt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sandbox
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: auth Google Cloud
      #   uses: google-github-actions/auth@v2
      #   with: 
      #     credentials_json: 

      - name: create_service_account_key_file
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 -d > service-account-key.json

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        run: gcloud auth activate-service-account --key-file=service-account-key.json

      # - name: auth GAR
      #   run: gcloud auth configure-docker secrets.GCP_REGION }}-docker.pkg.dev -q

      - name: build Docker image to GAR
        run: docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dbt/dbt-image:latest .

      - name: push Docker image
        run: docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dbt/dbt-image:latest

      - name: deploy Cloud Run Jobs
        run: gcloud run jobs deploy dbt --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dbt/dbt-image --region=${{ secrets.GCP_REGION }} --tasks=1 --cpu=1 --max-retries=0 --memory=512Mi --parallelism=1 --task-timeout=600 --region ${{ secrets.GCP_REGION }}

      - name: execute Cloud Run Jobs
        run: gcloud run jobs execute dbt --region=${{ secrets.GCP_REGION }}
