name: deploy dbt

on:
  push:
    branches:
      - main

jobs:
  deploy-dbt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sandbox
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'

      - name: Authenticate to Google Cloud
        run: | 
             echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > "${{ github.workspace }}/gcloud-key.json"
             gcloud auth activate-service-account --key-file="${{ github.workspace }}/gcloud-key.json"
             gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: build Docker image to GAR
        run: docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dbt/dbt-image:latest .

      - name: push Docker image
        run: docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dbt/dbt-image:latest

      - name: deploy Cloud Run Jobs
        run: gcloud run jobs deploy dbt --image ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dbt/dbt-image --region=${{ secrets.REGION }} --tasks=1 --cpu=1 --max-retries=0 --memory=512Mi --parallelism=1 --task-timeout=600 --region ${{ secrets.REGION }}

      - name: execute Cloud Run Jobs
        run: gcloud run jobs execute dbt --region=${{ secrets.REGION }}
