name: deploy dbt

on:
  push:
    branches:
      - main

jobs:
  deploy-dbt:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    defaults:
      run:
        working-directory: ./sandbox
    env: 
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
=======
    # defaults:
      # run:
      #   working-directory: ./sandbox
>>>>>>> 4b69bb8e82e0a9b271de9bab00d7025b3436559c
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

<<<<<<< HEAD
=======
      - name: auth Google Cloud
        uses: google-github-actions/auth@v2
        with: 
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

>>>>>>> 4b69bb8e82e0a9b271de9bab00d7025b3436559c
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
<<<<<<< HEAD
          project_id: $GCP_PROJECT_ID

      - name: auth Google Cloud
        uses: google-github-actions/auth@v2
        with: 
          credentials_json: $GCP_SERVICE_ACCOUNT_KEY

      - name: build Docker image to GAR
        run: docker build -t $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/dbt/dbt-image:latest .

      - name: push Docker image
        run: docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/dbt/dbt-image:latest

      - name: deploy Cloud Run Jobs
        run: gcloud run jobs deploy dbt --image $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/dbt/dbt-image --region=$GCP_REGION --tasks=1 --cpu=1 --max-retries=0 --memory=512Mi --parallelism=1 --task-timeout=600 --region $GCP_REGION

      - name: execute Cloud Run Jobs
        run: gcloud run jobs execute dbt --region=$GCP_REGION
=======
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: build Docker image to GAR
        run: docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dbt/dbt-image:latest .

      - name: push Docker image
        run: docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dbt/dbt-image:latest

      - name: deploy Cloud Run Jobs
        run: gcloud run jobs deploy dbt --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dbt/dbt-image --region=${{ secrets.GCP_REGION }} --tasks=1 --cpu=1 --max-retries=0 --memory=512Mi --parallelism=1 --task-timeout=600 --region ${{ secrets.GCP_REGION }}

      - name: execute Cloud Run Jobs
        run: gcloud run jobs execute dbt --region=${{ secrets.GCP_REGION }}
>>>>>>> 4b69bb8e82e0a9b271de9bab00d7025b3436559c
