name: deploy dbt

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-dbt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sandbox
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: auth Google Cloud
        uses: google-github-actions/auth@v2
        with: 
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: create_service_account_key_file
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | jq '.' > service-account-key.json

      - name: list
        run: ls -a

      - name: cat
        run: cat service-account-key.json

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: auth GAR
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev -q

      - name: build Docker image to GAR
        run: docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dbt/dbt-image:latest .

      - name: push Docker image
        run: docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dbt/dbt-image:latest

      - name: deploy Cloud Run Jobs
        run: gcloud run jobs deploy dbt --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dbt/dbt-image --region=${{ secrets.GCP_REGION }} --tasks=1 --cpu=1 --max-retries=0 --memory=512Mi --parallelism=1 --task-timeout=600 --region ${{ secrets.GCP_REGION }}

      - name: execute Cloud Run Jobs
        run: gcloud run jobs execute dbt --region=${{ secrets.GCP_REGION }}
